name: Build and Test

on:
  push:
  
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  test-security:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]

    steps:
    - name: Checkout Repo 
      uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install Dependencies    
      run: npm install
    - name: Start App
      run: npm start &
    - name: Test App
      run: npm run test-npm-security



  build-test:

    needs: test-security
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo 
      uses: actions/checkout@v3
    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    - name: Install Dependencies    
      run: npm install
    - name: Start App
      run: npm start &
    - name: Test App
      run: npm test
  
